POST http://localhost:8080/category/save
Content-Type: application/json

{
  "name": "category 1",
  "code" : "category code 1",
}

###
PUT http://localhost:8080/category/update
Content-Type: application/json

{
  "id": 41,
  "name": "user 12345",
  "email" : "email13@gmail13.com",
  
}

###
DELETE http://localhost:8080/category/delete
Content-Type: application/json

{
  "id": 42
}

###
POST http://localhost:8080/category/search
Content-Type: application/json

{
  "idList": []
}

