POST http://localhost:8080/customer/save
Content-Type: application/json

{
  "company_name": "company_3",
  "customer_name": "customer_name_3",
  "contact_title": "contact_title_3",
  "address": "address_3",
  "city": "city_3",
  "region": "region_3",
  "postal_code": 3900,
  "country": "country_3"
}

###
PUT http://localhost:8080/customer/update
Content-Type: application/json

{
  "id": 41,
  "name": "user 12345",
  "email" : "email13@gmail13.com"

}

###
DELETE http://localhost:8080/customer/delete
Content-Type: application/json

{
  "id": 1
}

###
POST http://localhost:8080/customer/search
Content-Type: application/json

{
  "idList": []
}

###
POST http://localhost:8080/customer/search-with-order-with-orderdetail
Content-Type: application/json

{
  "idList": []
}