POST http://localhost:8080/employee/save
Content-Type: application/json

{
  "first_name": "first_name_6",
  "last_name" : "last_name_6",
  "title": "title_6",
  "title_of_courtesy": "courtesy_6",
  "birth_date": "2002-12-30",
  "hire_date": "2022-12-30",
  "address": "address_6",
  "city": "city_6",
  "postal_code" : "600",
  "region" : "dhaka"
}

###
PUT http://localhost:8080/employee/update
Content-Type: application/json

{
  "id": 41,
  "name": "user 12345",
  "email" : "email13@gmail13.com"

}

###
DELETE http://localhost:8080/employee/delete
Content-Type: application/json

{
  "id": 1
}

###
POST http://localhost:8080/employee/search
Content-Type: application/json

{
  "idList": []
}

###
POST http://localhost:8080/employee/search-with-territory
Content-Type: application/json

{
"idList": []
}