POST http://localhost:8080/floor/save
Content-Type: application/json

{
  "name": "user 502",
  "code" : "email112@gmail.com",
}

###
PUT http://localhost:8080/floor/update
Content-Type: application/json

{
  "id": 41,
  "name": "user 12345",
  "email" : "email13@gmail13.com"
  
}

###
DELETE http://localhost:8080/floor/delete
Content-Type: application/json

{
  "id": 42
}

###
POST http://localhost:8080/floor/search
Content-Type: application/json

{
  "idList": []
}

###
POST http://localhost:8080/floor/search-with-room
Content-Type: application/json

{
"idList": []
}