POST http://localhost:8080/order-info-detail/save
Content-Type: application/json

{
"orderInfo": {
  "id":1
},
  "orderInfoId": 1,
  "product": {
    "id":1
  },
  "productId": 1,
  "unit_price": 100,
  "quantity": 10,
  "discount": null
}

###
PUT http://localhost:8080/order-info-detail/update
Content-Type: application/json

{
  "id": 41,
}

###
DELETE http://localhost:8080/order-info-detail/delete
Content-Type: application/json

{
  "id": 1
}

###
POST http://localhost:8080/order-info-detail/search
Content-Type: application/json

{
  "idList": []
}