POST http://localhost:8080/order-info/save
Content-Type: application/json

{
"customer": {
  "id": 2
},
"employee": {
    "id":2
},

"order_date": "2023-12-12",
"required_date": "2023-12-12",
"shipped_date": "2023-12-12",
"ship_via": null,
"freight": null,
"ship_name": "ship 2"
}

###
PUT http://localhost:8080/order-info/update
Content-Type: application/json

{
  "id": 41,
  "name": "user 12345",
  "email" : "email13@gmail13.com"

}

###
DELETE http://localhost:8080/order-info/delete
Content-Type: application/json

{
  "id": 1
}

###
POST http://localhost:8080/order-info/search
Content-Type: application/json

{
  "idList": []
}
