POST http://localhost:8080/role/save
Content-Type: application/json

{
  "name": "admin",
  "userInfoRoleList": 
  {
    "userInfo_id":1,
    "role_id":1
  }
}

###
POST http://localhost:8080/role/search
Content-Type: application/json

{
  "idList": []
}

###
PUT http://localhost:8080/role/update/1000
Content-Type: application/json

{
  "id": 12,
  "name": "user 60",
  "userInfoRoleList": []
}

###
DELETE http://localhost:8080/role/delete/1000
Content-Type: application/json

{
  "id": 7,
   
}