POST http://localhost:8080/role/save
Content-Type: application/json

{
  "name": "admin 15"
}



###
PUT http://localhost:8080/role/update
Content-Type: application/json

{
  "id": 2,
  "name": "admin 124"
}

###
DELETE http://localhost:8080/role/delete
Content-Type: application/json

{
  "id": 2
}

###
POST http://localhost:8080/role/search
Content-Type: application/json

{
  "idList": []
}