POST http://localhost:8080/territory/save
Content-Type: application/json

{
  "territory_description": "description 1",
}


###
PUT http://localhost:8080/territory/update
Content-Type: application/json

{
  "id": 41,
  "name": "user 12345",
  "email" : "email13@gmail13.com"

}

###
DELETE http://localhost:8080/territory/delete
Content-Type: application/json

{
  "id": 1
}

###
POST http://localhost:8080/territory/search
Content-Type: application/json

{
  "idList": [1,2]
}

###
POST http://localhost:8080/territory/search-with-employee
Content-Type: application/json

{
"idList": []
}