POST http://localhost:8080/user-info/save
Content-Type: application/json

{
  "name": "user 502",
  "email" : "email112@gmail.com",
  "mobile": 12345612
}

###
PUT http://localhost:8080/user-info/update
Content-Type: application/json

{
  "id": 41,
  "name": "user 12345",
  "email" : "email13@gmail13.com",
  "mobile": 13
}

###
DELETE http://localhost:8080/user-info/delete
Content-Type: application/json

{
  "id": 42
}

###
POST http://localhost:8080/user-info/search
Content-Type: application/json

{
  "idList": []
}

###
POST http://localhost:8080/user-info/searchWithUserInfoRole
Content-Type: application/json
