POST http://localhost:8080/user/save
Content-Type: application/json

{
  "name": "user 11",
  "email" : "email11@gmail.com",
  "mobile": 123456,
  "userInfoRoleList":
  {
    
    "userInfo_id":1,
    "role_id": 1,
  },
   {
    "userInfo_id":1,
    "role_id": 2,
  },
   {
    "userInfo_id":1,
    "role_id": 3,
  }
}
###

POST http://localhost:8080/user/search
Content-Type: application/json

{
  "idList": []
}
###

PUT http://localhost:8080/user/update/13
Content-Type: application/json

{
  "id": 13,
  "name": "user 13",
  "email" : "email13@gmail13.com",
  "mobile": 13,
   "userInfoRoleList":
  {
    
    "userInfo_id":1,
    "role_id": 1,
  },
   {
    "userInfo_id":1,
    "role_id": 4,
  },
   {
    "userInfo_id":1,
    "role_id": 5,
  }

}

###
DELETE http://localhost:8080/user/delete/1000
Content-Type: application/json

{
  "id": 13
}