POST http://localhost:8080/user/save
Content-Type: application/json

{
  "name": "user 11",
  "email" : "email11@gmail.com",
  "mobile": 123456,
  "userInfoRoleList":
  {
    "role_id": 1,
    "userInfo_id":1
  }
}
###

POST http://localhost:8080/user/search
Content-Type: application/json

{
  "idList": []

  
}
###

PUT http://localhost:8080/user/update/13
Content-Type: application/json

{
  "id": 13,
  "name": "user 13",
  "email" : "email13@gmail13.com",
  "mobile": 13,
  "userInfoRoleList":

}

###
DELETE http://localhost:8080/user/delete/13
Content-Type: application/json

{
  "id": 13
}